name: Update Version Badge

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags, e.g., v1.0.0

jobs:
  update-badge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get latest tag
        id: get_latest_tag
        run: echo "LATEST_TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

      - name: Update README.md
        run: |
          # Construct the new badge URL
          BADGE_URL="https://img.shields.io/badge/version-${{ env.LATEST_TAG }}-blue"
          
          # Update the README.md with the new badge URL
          sed -i.bak "s|https://img.shields.io/badge/version-[^ ]*|$BADGE_URL|g" README.md

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update version badge to $LATEST_TAG" || echo "No changes to commit"
          git push
